### ISSUE TITLE
Z_CMD reset by fisher refresh

### ISSUE THREAD

**Issue by pikeas** [jethrokuan/z#85]
```
$ echo $Z_CMD
j
$ fisher
To completely erase z's data, remove:
/Users/pikeas/.local/share/z/data
fetching https://codeload.github.com/jethrokuan/z/tar.gz/master
linking ~/.config/fish/conf.d/done.fish
linking ~/.config/fish/functions/__z.fish
linking ~/.config/fish/functions/__z_add.fish
linking ~/.config/fish/functions/__z_clean.fish
linking ~/.config/fish/functions/__z_complete.fish
linking ~/.config/fish/conf.d/z.fish
...
updated 4 packages in 2.26s
$ echo $Z_CMD
z
```

**Comment by jethrokuan** [comment]
The problem is now `fisher` does a complete teardown and setup for all plugins. it runs:

```
https://github.com/jethrokuan/z/blob/master/functions/uninstall.fish
```

So now it's between:

1. Having lingering environment variables after an uninstall, or
2. the behaviour you're seeing

**Comment by jorgebucaran** [comment]
https://github.com/jorgebucaran/fisher/issues/527

**Comment by jorgebucaran** [comment]
Fixed in [4.x](https://github.com/jorgebucaran/fisher/releases/tag/4.0.0). :tada:

**Comment by demartini** [comment]
I am still having the same problem.

fish 3.1.2
fisher 4.1.0

**Comment by jorgebucaran** [comment]
@jorgebucaran Are you using the latest Z?

**Comment by jorgebucaran** [comment]
@demartini Are you using the latest Z?

**Comment by demartini** [comment]
> @demartini Are you using the latest Z?

Yes, I installed and reinstalled it several times, I even tested it with Oh My Fish.

**Comment by jorgebucaran** [comment]
I think this should do it (https://github.com/jethrokuan/z/pull/94).

```console
▸ fisher install jorgebucaran/z@patch-1
fisher install version 4.1.0
fetching https://codeload.github.com/jorgebucaran/z/tar.gz/patch-1
installing jorgebucaran/z@patch-1
           /Users/jb/.config/fish/functions/__z.fish
           /Users/jb/.config/fish/functions/__z_add.fish
           /Users/jb/.config/fish/functions/__z_clean.fish
           /Users/jb/.config/fish/functions/__z_complete.fish
           /Users/jb/.config/fish/conf.d/z.fish
installed 1 plugin/s
▸ echo $Z_CMD
z
▸ set Z_CMD j
▸ fisher update jorgebucaran/z@patch-1 
fisher update version 4.1.0
fetching https://codeload.github.com/jorgebucaran/z/tar.gz/patch-1
installing jorgebucaran/z@patch-1
           /Users/jb/.config/fish/functions/__z.fish
           /Users/jb/.config/fish/functions/__z_add.fish
           /Users/jb/.config/fish/functions/__z_clean.fish
           /Users/jb/.config/fish/functions/__z_complete.fish
           /Users/jb/.config/fish/conf.d/z.fish
updated 1 plugin/s
▸ echo $Z_CMD
j
````

cc @jethrokuan @demartini @pikeas

**Comment by demartini** [comment]
> I think this should do it (#94).

Many thank @jorgebucaran, it's working like a charm.

**Comment by jorgebucaran** [comment]
@jethrokuan Close 😉
